#!/bin/bash

if [ $(id -u) != "0" ]; then
    echo "ERROR: You must be root to run this script!"
    exit 1;
fi

CONFIG="redis.conf"
PORT=$(grep -v "#" redis.conf | grep port | awk '{ print $2 }')
PID=$(netstat -antp | grep $PORT | grep redis-server | awk '{ print $7 }' | sed 's/\/.*$//g')
LOG="redis.log"

REDIS="/usr/local/bin/redis-server"

start() {
    echo "Starting redis-server"
    nohup $REDIS $CONFIG > $LOG 2>&1 &
    RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
        echo done
    else
        echo done
    fi
    return $RETVAL
}

stop() {
    echo $"Stopping redis-server"
    kill -TERM $PID >/dev/null 2>&1
    RETVAL=$?
    if [ $RETVAL -eq 0 ] ;then
            echo "Waiting for Redis to shutdown .."
            while([ $RETVAL -eq 0 ]) do
                stop;
            done;
    else
            echo "done"
    fi
    return $RETVAL

}

restart() {
    stop
    start
}

status() {
    if [ $PID ] ;then
        echo "redis-server is running at $PID"
    else
        echo "redis-server is not running"
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        status
        RETVAL=$?
        ;;
    *)
        echo $"Usage: {start|stop|status|restart}"
        RETVAL=1
esac

exit $RETVAL